---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: satcom886/arch-builder:base
  commands:
  - build-aur yay
  - find /home/builder/built/ -iname *pkg.tar* -exec pacman -U --noconfirm "{}"  \;
