name: Build the builder image

on:
  push:
    paths:
      - '01_builder/Dockerfile'
      - '01_builder/.arch_build_scripts/*'
      - '.github/workflows/builder.yml'
  workflow_run:
    workflows: [Build the base image]
    types:
      - completed

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: 01_builder/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.actor }}/arch-builder:latest
