name: Build the arch-repo image

on:
  push:
    paths:
      - 'arch-repo/Dockerfile'
      - 'arch-repo/entrypoint.sh'
      - 'arch-repo/add-package.sh'
      - '.github/workflows/repo.yml'
  workflow_run:
    workflows: [Build the base image]
    types:
      - completed

jobs:
  arch-repo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: arch-repo/
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/${{ github.actor }}/arch-repo:latest
